kind: Service
apiVersion: v1
metadata:
  name: swap-front-svc
  namespace: chainx-prod
  labels:
    app: swap-front-svc
spec:
  ports:
    - name: tcp-main
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: swap-front-svc
status:
  loadBalancer: {}
